language: node_js

env:
    # HEROKU_API_KEY
    - secure: "vtVB22ICBgR7cX4jKAY4+A8JggltGZunElVIbc7QPpUjVdJB2NPUhA9G7meL1DVqNCSIE7znSXZKbi68kK14xYOAjKK0WFJMp8duXywN3cLRMNOtiN7ZZpqjXKOIsg4QvxS8jbhgpj6oxxbJdENoUd5FSydXfFfBu7KWC4qPlLco1M8MyMeqALtEOHoBj0WoS02jVx+RD4upqaDf1h7VW26+ExtlANfupy/i/ZYHSJGs8sR2S+WBGvzHQif/IlMy7CitcDAlaJyKVKiCUMHDnf1O4abodNRpq8rsjvLOrvNAFY3goTe/5kwXUvi3dWUouUFQz+BE+0vWUVJH+AsZI36M70u4C/U33qr2JFba0fwh5kqGz6vorqwdR0DgyDQ0/hJ31coeWMtQy4t7S/gBTN8HSo0AGJDI0nIR4gI9cZMHRCC5vGiINBY6WRvfTBj+AdWGDTj8RkZGBxs/BsNbDfwdn5BRbV2bkZ1RPb7vUZtFcHzOTv+QKRNXtVzkK024D3RYdb8y5sWIgG0ffB7MtJz0J58s6y/o3aatHrCor9SkmfK5Fdtb+EJuwE5olO8P2SaMCjLfD2x7YJrOFZTlyH7VIkelpb2jDJWpM1ag0+ouNMwtipVwIoNS5Y0u0iWUKEGLK6Rj6KUO5soKbt1rO70bg0wZuZYRNOji9XYZ/gk="

script:
    - yarn run lint
    - yarn run build

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app:
        master: js-react-weather-app
    skip_cleanup: true
