export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_HISTORICAL_WEATHER_SUCCESS =
    'FETCH_HISTORICAL_WEATHER_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
